name: Track Changed Files

on:
  push:
    branches:
      - main

jobs:
  detect-changes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Detect changed files
        run: |
          # Compare with the previous commit
          git fetch origin main --depth=2
          git diff --name-only --diff-filter=AM HEAD^ HEAD > updated_files.txt
